ENH: Clean `itk::WrapExtrapolateImageFunction` Python wrapping
InsightSoftwareConsortium/ITKNDReg pull request #17
Opened 2019-03-24 13:15 UTC by jhlegarreta

Clean `itk::WrapExtrapolateImageFunction` Python wrapping: the parent
class `itk::ExtrapolateImageFunction` was wrapped in ITK in [PR
610](https://github.com/InsightSoftwareConsortium/ITK/pull/610).

2019-03-24 13:16 UTC, jhlegarreta commented
Thanks for having wrapped the parent class @thewtex !

2019-03-24 19:43 UTC, thewtex requested changes
:+1: thanks @jhlegarreta !

We should wait until ITK 5.0 RC 1 is released, then update the ITK version in `azure-pipelines.yml` so we have the required wrapping in ITK.

2019-08-22 02:38 UTC, thewtex commented
Rebasing...

2019-08-22 02:41 UTC, thewtex approved these changes

2019-08-22 03:57 UTC, merged